version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: cron
          cronjob: '17 3 9 * *'
          timezone: Europe/Berlin
      cooldown:
          default-days: 7
      open-pull-requests-limit: 15
      assignees:
          - Musashi1965
      versioning-strategy: increase
      ignore:
          - dependency-name: '@types/node'
            update-types:
                - version-update:semver-major
          - dependency-name: 'typescript'
            update-types:
                - version-update:semver-major
          - dependency-name: '@vitejs/plugin-react'
            versions:
                - '6.1.0'
          - dependency-name: '@types/react-dom'
            versions:
                - '19.2.5'
          - dependency-name: '@iobroker/json-config'
            versions:
                - '9.0.23'
          - dependency-name: '@module-federation/runtime'
            versions:
                - '2.9.0'
          - dependency-name: '@types/react'
            versions:
                - '19.2.18'
          - dependency-name: '@module-federation/vite'
            versions:
                - '1.21.0'
          - dependency-name: 'vite'
            versions:
                - '8.2.2'

    - package-ecosystem: github-actions
      directory: '/'
      schedule:
          interval: cron
          cronjob: '41 3 23 * *'
          timezone: Europe/Berlin
      open-pull-requests-limit: 15
      assignees:
          - Musashi1965
